services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      API_BASE_INTERNAL: http://localhost:8000
      NEXT_PUBLIC_API_BASE: http://localhost:8000
      FRONTEND_INTERNAL: http://host.docker.internal:3000
    ports:
      - "3000:3000"
      - "8000:8000"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
