"""add featured boolean field to Skill

Revision ID: 496e419836ad
Revises: df2b66ebfc91
Create Date: 2025-06-29 11:19:22.027195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496e419836ad'
down_revision: Union[str, Sequence[str], None] = 'df2b66ebfc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('featured', sa.Boolean(), nullable=False, server_default="false"))
    op.alter_column('worksegment', 'summary',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worksegment', 'summary',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.drop_column('skill', 'featured')
    # ### end Alembic commands ###
