"""add order field to Info

Revision ID: 559d9ea146a5
Revises: 7936c9a3c674
Create Date: 2025-06-29 18:22:26.742058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559d9ea146a5'
down_revision: Union[str, Sequence[str], None] = '7936c9a3c674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'order')
    # ### end Alembic commands ###
