"""User info model

Revision ID: 7936c9a3c674
Revises: 4a2bef9460a2
Create Date: 2025-06-29 18:19:38.228384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7936c9a3c674'
down_revision: Union[str, Sequence[str], None] = '4a2bef9460a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('linked_in', sa.String(length=50), nullable=False),
    sa.Column('calendly', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('citizenship', sa.String(length=30), nullable=False),
    sa.Column('github', sa.String(length=75), nullable=False),
    sa.Column('resume_download', sa.String(length=75), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###
