"""add order field to Info

Revision ID: 9073ec9dde22
Revises: 559d9ea146a5
Create Date: 2025-06-29 18:25:01.383481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9073ec9dde22'
down_revision: Union[str, Sequence[str], None] = '559d9ea146a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info', 'linked_in',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('info', 'calendly',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('info', 'citizenship',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=75),
               existing_nullable=False)
    op.alter_column('info', 'github',
               existing_type=sa.VARCHAR(length=75),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info', 'github',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=75),
               existing_nullable=False)
    op.alter_column('info', 'citizenship',
               existing_type=sa.String(length=75),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('info', 'calendly',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('info', 'linked_in',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
