"""Create Resume models and use Base class to hold id fields

Revision ID: b100b3ea0e93
Revises: f3d5968135e7
Create Date: 2025-06-28 20:18:01.414925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b100b3ea0e93'
down_revision: Union[str, Sequence[str], None] = 'f3d5968135e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_about_id'), table_name='about')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_slide_id'), table_name='slide')
    op.drop_index(op.f('ix_story_id'), table_name='story')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_story_id'), 'story', ['id'], unique=False)
    op.create_index(op.f('ix_slide_id'), 'slide', ['id'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_about_id'), 'about', ['id'], unique=False)
    # ### end Alembic commands ###
