"""Create Resume models

Revision ID: bc5597ba99a5
Revises: b100b3ea0e93
Create Date: 2025-06-28 20:24:22.843169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5597ba99a5'
down_revision: Union[str, Sequence[str], None] = 'b100b3ea0e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('summary_header', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('skills_header', sa.String(length=50), nullable=False),
    sa.Column('work_header', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worksegment',
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('href', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('work_range', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('work_type', sa.Enum('HYBRID', 'REMOTE', 'ONSITE', name='worktype'), nullable=False),
    sa.Column('bullet_1', sa.Text(), nullable=False),
    sa.Column('bullet_2', sa.Text(), nullable=False),
    sa.Column('bullet_3', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('button_text', sa.String(length=25), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skilldescription',
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worksegmentexpansion',
    sa.Column('bullet', sa.String(), nullable=False),
    sa.Column('work_segment_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_segment_id'], ['worksegment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worksegmentexpansion')
    op.drop_table('skilldescription')
    op.drop_table('worksegment')
    op.drop_table('skill')
    op.drop_table('resume')
    # ### end Alembic commands ###
