"""Add summary field

Revision ID: df2b66ebfc91
Revises: bc5597ba99a5
Create Date: 2025-06-28 21:45:46.858389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2b66ebfc91'
down_revision: Union[str, Sequence[str], None] = 'bc5597ba99a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worksegment', sa.Column('summary', sa.Text(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worksegment', 'summary')
    # ### end Alembic commands ###
